package com.video.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VideoImagenAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVideoImagenAllPropertiesEquals(VideoImagen expected, VideoImagen actual) {
        assertVideoImagenAutoGeneratedPropertiesEquals(expected, actual);
        assertVideoImagenAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVideoImagenAllUpdatablePropertiesEquals(VideoImagen expected, VideoImagen actual) {
        assertVideoImagenUpdatableFieldsEquals(expected, actual);
        assertVideoImagenUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVideoImagenAutoGeneratedPropertiesEquals(VideoImagen expected, VideoImagen actual) {
        assertThat(actual)
            .as("Verify VideoImagen auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVideoImagenUpdatableFieldsEquals(VideoImagen expected, VideoImagen actual) {
        assertThat(actual)
            .as("Verify VideoImagen relevant properties")
            .satisfies(a -> assertThat(a.getFilename()).as("check filename").isEqualTo(expected.getFilename()))
            .satisfies(a -> assertThat(a.getOrden()).as("check orden").isEqualTo(expected.getOrden()))
            .satisfies(a ->
                assertThat(a.getDuracionIndividual()).as("check duracionIndividual").isEqualTo(expected.getDuracionIndividual())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVideoImagenUpdatableRelationshipsEquals(VideoImagen expected, VideoImagen actual) {
        assertThat(actual)
            .as("Verify VideoImagen relationships")
            .satisfies(a -> assertThat(a.getVideo()).as("check video").isEqualTo(expected.getVideo()));
    }
}
