package com.video.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VideoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVideoAllPropertiesEquals(Video expected, Video actual) {
        assertVideoAutoGeneratedPropertiesEquals(expected, actual);
        assertVideoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVideoAllUpdatablePropertiesEquals(Video expected, Video actual) {
        assertVideoUpdatableFieldsEquals(expected, actual);
        assertVideoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVideoAutoGeneratedPropertiesEquals(Video expected, Video actual) {
        assertThat(actual)
            .as("Verify Video auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVideoUpdatableFieldsEquals(Video expected, Video actual) {
        assertThat(actual)
            .as("Verify Video relevant properties")
            .satisfies(a -> assertThat(a.getTitulo()).as("check titulo").isEqualTo(expected.getTitulo()))
            .satisfies(a -> assertThat(a.getAudioFilename()).as("check audioFilename").isEqualTo(expected.getAudioFilename()))
            .satisfies(a -> assertThat(a.getTieneAudio()).as("check tieneAudio").isEqualTo(expected.getTieneAudio()))
            .satisfies(a ->
                assertThat(a.getDuracionTransicion()).as("check duracionTransicion").isEqualTo(expected.getDuracionTransicion())
            )
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a -> assertThat(a.getFechaCreacion()).as("check fechaCreacion").isEqualTo(expected.getFechaCreacion()))
            .satisfies(a -> assertThat(a.getFechaDescarga()).as("check fechaDescarga").isEqualTo(expected.getFechaDescarga()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVideoUpdatableRelationshipsEquals(Video expected, Video actual) {
        // empty method
    }
}
