package com.video.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VideoCreditoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVideoCreditoAllPropertiesEquals(VideoCredito expected, VideoCredito actual) {
        assertVideoCreditoAutoGeneratedPropertiesEquals(expected, actual);
        assertVideoCreditoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVideoCreditoAllUpdatablePropertiesEquals(VideoCredito expected, VideoCredito actual) {
        assertVideoCreditoUpdatableFieldsEquals(expected, actual);
        assertVideoCreditoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVideoCreditoAutoGeneratedPropertiesEquals(VideoCredito expected, VideoCredito actual) {
        assertThat(actual)
            .as("Verify VideoCredito auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVideoCreditoUpdatableFieldsEquals(VideoCredito expected, VideoCredito actual) {
        assertThat(actual)
            .as("Verify VideoCredito relevant properties")
            .satisfies(a -> assertThat(a.getVideosConsumidos()).as("check videosConsumidos").isEqualTo(expected.getVideosConsumidos()))
            .satisfies(a -> assertThat(a.getVideosDisponibles()).as("check videosDisponibles").isEqualTo(expected.getVideosDisponibles()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVideoCreditoUpdatableRelationshipsEquals(VideoCredito expected, VideoCredito actual) {
        // empty method
    }
}
